### ISSUE TITLE
Programs misbehave on PAL

### ISSUE THREAD

**Issue by josefwegner** [tschak909/amiga-pac-man#1]
Hi Thomas,

your Pac-Man test harnesses misbehave on PAL Amigas. I have no clue why, but for example DrawStage will not show the icons, and trying to move the screen will result in a GURU #8201 0000 (Not enough memory?!?).

On first glance I do not see any parts that could cause issues. Maybe the OS does not like that you open the screen with NTSC size?

**Comment by tschak909** [comment]
Thanks for testing!

The drawStage test harness has a fatal bug which I need to fix, this
happens on all machines.

Do the other test harnesses work okay?
-Thom

**Comment by josefwegner** [comment]
Hi Thom,

The other programs work fine on PAL. It is just DrawStage.

Thank you for looking into this.

**Comment by josefwegner** [comment]
Hi Thom,

What is the fatal bug?

Thanks,
Josef
